options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # metabase
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials candle-cluster --zone europe-west1 --project strange-mind-410708
        kubectl apply -f metabase.yaml
        kubectl rollout status deployment metabase-deployment

  # mongo
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f mongo-pvc.yaml
        kubectl create secret generic mongo-secrets \
          --from-literal=mongo-user=$(gcloud secrets versions access latest --secret=mongo-user) \
          --from-literal=mongo-password=$(gcloud secrets versions access latest --secret=mongo-password) || true

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f mongo.yaml
        kubectl rollout status deployment mongo-deployment

  # ingestor
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/strange-mind-410708/candle-scrappy/ingestor:latest'
    - '-f'
    - './ingestor/Dockerfile'
    - './ingestor'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/strange-mind-410708/candle-scrappy/ingestor:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f ingestor-config.yaml

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f ingestor.yaml
        kubectl rollout status deployment ingestor-deployment
    
  # mysql
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f mysql-config.yaml
        kubectl create secret generic mysql-secrets \
          --from-literal=mysql-user=$(gcloud secrets versions access latest --secret=mysql-user) \
          --from-literal=mysql-database=$(gcloud secrets versions access latest --secret=mysql-database) \
          --from-literal=mysql-password=$(gcloud secrets versions access latest --secret=mysql-password) \
          --from-literal=mysql-root-password=$(gcloud secrets versions access latest --secret=mysql-root-password) || true

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f mysql.yaml
        kubectl rollout status deployment mysql-deployment  

  # etl
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'europe-west1-docker.pkg.dev/strange-mind-410708/candle-scrappy/etl:latest'
    - '-f'
    - './etl/Dockerfile'
    - './etl'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/strange-mind-410708/candle-scrappy/etl:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f etl.yaml
        kubectl rollout status deployment etl-deployment