options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials candle-cluster --zone europe-west1 --project strange-mind-410708
        kubectl apply -f metabase.yaml
        kubectl rollout status deployment metabase-deployment

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f mongo-config.yaml
        kubectl apply -f mongo-pvc.yaml
        kubectl create secret generic mongo-secrets \
          --from-literal=mongo-user=$(gcloud secrets versions access latest --secret=mongo-user) \
          --from-literal=mongo-password=$(gcloud secrets versions access latest --secret=mongo-password)

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f mongo.yaml
        kubectl rollout status deployment mongo-deployment
