version: '3'
services:
  ingestor:
    build: ./ingestor/
    container_name: ingestor
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
  
  etl:
    build: ./etl/
    container_name: etl
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
  

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_conf/:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql

    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo:/data/db

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MYSQL_DATABASE}
      MB_DB_PORT: ${MYSQL_PORT}
      MB_DB_USER: ${MYSQL_USER}
      MB_DB_PASS: ${MYSQL_PASSWORD}
      MB_DB_HOST: mysql

volumes:
  mongo:
  mysql:
  metabase: